name: 'sfdx-source-deploy'
description: 'Deploy a changeset to a GH environment'
author: 'matthew-gladman'
inputs:
  environment-name:
    required: true
    description: 'The environment name that will show in GitHub'
  action:
    required: true
    description: 'Either `create` or `deploy`'
runs:
  using: 'node16'
  main: 'dist/index.js'
